version: '3'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/KaraokeSongPhung
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=KaraokeSongPhung
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  docker-nest-postgres:
